sudo: required
services:
  - docker

before_install:
  - docker build -t dock-react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true dock-react-test npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-starter-1"
  env: "docker-react-starter-1-env"
  bucket_name: "elasticbeanstalk-ap-south-1-102578530890"
  bucket_path: "docker-react-starter-1-env"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
